"""Pydantic schemas for request/response validation."""

from app.schemas.auth import DeviceCodeRequest, DeviceCodeResponse, TokenRequest, TokenResponse
from app.schemas.lint import (
    LintIssueCreate,
    LintIssueListResponse,
    LintIssueResponse,
    LintRuleInfo,
    LintRulesResponse,
    LintRunCreate,
    LintRunDetailResponse,
    LintRunListResponse,
    LintRunResponse,
    LintSummaryResponse,
    LintTriggerResponse,
)
from app.schemas.ontology import OntologyCreate, OntologyResponse, OntologyUpdate
from app.schemas.owl_class import OWLClassCreate, OWLClassResponse, OWLClassUpdate
from app.schemas.owl_property import OWLPropertyCreate, OWLPropertyResponse, OWLPropertyUpdate
from app.schemas.pull_request import (
    BranchCreate,
    BranchDeleteRequest,
    BranchInfo,
    BranchListResponse,
    BranchSwitchRequest,
    CommentCreate,
    CommentListResponse,
    CommentResponse,
    CommentUpdate,
    GitHubIntegrationCreate,
    GitHubIntegrationResponse,
    GitHubIntegrationUpdate,
    PRCommit,
    PRCommitListResponse,
    PRCreate,
    PRDiffResponse,
    PRFileChange,
    PRListResponse,
    PRMergeRequest,
    PRMergeResponse,
    PRResponse,
    PRSettingsResponse,
    PRSettingsUpdate,
    PRUpdate,
    PRUser,
    ReviewCreate,
    ReviewListResponse,
    ReviewResponse,
    SemanticDiffResponse,
    TripleChange,
)

__all__ = [
    "DeviceCodeRequest",
    "DeviceCodeResponse",
    "TokenRequest",
    "TokenResponse",
    # Lint schemas
    "LintIssueCreate",
    "LintIssueListResponse",
    "LintIssueResponse",
    "LintRuleInfo",
    "LintRulesResponse",
    "LintRunCreate",
    "LintRunDetailResponse",
    "LintRunListResponse",
    "LintRunResponse",
    "LintSummaryResponse",
    "LintTriggerResponse",
    # Ontology schemas
    "OntologyCreate",
    "OntologyResponse",
    "OntologyUpdate",
    "OWLClassCreate",
    "OWLClassResponse",
    "OWLClassUpdate",
    "OWLPropertyCreate",
    "OWLPropertyResponse",
    "OWLPropertyUpdate",
    # Pull request schemas
    "BranchCreate",
    "BranchDeleteRequest",
    "BranchInfo",
    "BranchListResponse",
    "BranchSwitchRequest",
    "CommentCreate",
    "CommentListResponse",
    "CommentResponse",
    "CommentUpdate",
    "GitHubIntegrationCreate",
    "GitHubIntegrationResponse",
    "GitHubIntegrationUpdate",
    "PRCommit",
    "PRCommitListResponse",
    "PRCreate",
    "PRDiffResponse",
    "PRFileChange",
    "PRListResponse",
    "PRMergeRequest",
    "PRMergeResponse",
    "PRResponse",
    "PRSettingsResponse",
    "PRSettingsUpdate",
    "PRUpdate",
    "PRUser",
    "ReviewCreate",
    "ReviewListResponse",
    "ReviewResponse",
    "SemanticDiffResponse",
    "TripleChange",
]
