FirstInstance:
  InstanceName: "OntoKit"
  DefaultLanguage: "en"
  Org:
    Name: "OntoKit"
    Human:
      UserName: "admin"
      FirstName: "Admin"
      LastName: "User"
      NickName: "admin"
      DisplayName: "Admin User"
      Email:
        Address: "admin@localhost"
        Verified: true
      PreferredLanguage: "en"
      Password: "Admin123!"
      PasswordChangeRequired: false
