"""add author name and email to pull_requests

Revision ID: 295fa3db0e38
Revises: 0c4545e3814e
Create Date: 2026-02-12 14:28:06.300382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '295fa3db0e38'
down_revision: Union[str, Sequence[str], None] = '0c4545e3814e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pull_requests', sa.Column('author_name', sa.String(length=255), nullable=True))
    op.add_column('pull_requests', sa.Column('author_email', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pull_requests', 'author_email')
    op.drop_column('pull_requests', 'author_name')
    # ### end Alembic commands ###
