"""Add label_preferences to projects

Revision ID: e68f6b98b09b
Revises: a1b2c3d4e5f6
Create Date: 2026-02-09 16:38:16.825430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e68f6b98b09b'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_members_user_id'), table_name='project_members')
    op.add_column('projects', sa.Column('label_preferences', sa.String(length=2000), nullable=True))
    op.drop_index(op.f('ix_projects_is_public'), table_name='projects')
    op.drop_index(op.f('ix_projects_owner_id'), table_name='projects')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_projects_owner_id'), 'projects', ['owner_id'], unique=False)
    op.create_index(op.f('ix_projects_is_public'), 'projects', ['is_public'], unique=False)
    op.drop_column('projects', 'label_preferences')
    op.create_index(op.f('ix_project_members_user_id'), 'project_members', ['user_id'], unique=False)
    # ### end Alembic commands ###
